### ISSUE TITLE
ImGui crashes the game easily

### ISSUE THREAD

**Issue by Cai1Hsu** [Cai1Hsu/DanmakuEngine#65]
Click either button in the menu crashes the game. This probably has to do with the incorrectly pointed memory. 

Sometimes we receives the exception below:
```ascii
24-03-28 13:39:59.801 [Error]: [Thread-Update] Unhandled exception: Arithmetic operation resulted in an overflow.
   at DanmakuEngine.DearImgui.Graphics.ImguiDrawDataSnapshot.WriteNewFrame(ImDrawDataPtr src) in /home/caiyi/repos/Danmaku!/DanmakuEngine/DearImgui/Graphics/ImguiDrawDataSnapshot.cs:line 66
   at DanmakuEngine.DearImgui.Imgui.Update() in /home/caiyi/repos/Danmaku!/DanmakuEngine/DearImgui/Imgui_Frame.cs:line 34
   at DanmakuEngine.Engine.GameHost.Update() in /home/caiyi/repos/Danmaku!/DanmakuEngine/Engine/GameHost.cs:line 204
   at DanmakuEngine.Scheduling.FrameExecutor.RunFrame() in /home/caiyi/repos/Danmaku!/DanmakuEngine/Scheduling/FrameExecutor.cs:line 40
   at DanmakuEngine.Scheduling.ThrottledExecutor.RunFrame() in /home/caiyi/repos/Danmaku!/DanmakuEngine/Scheduling/ThrottledExecutor.cs:line 33
   at DanmakuEngine.Threading.GameThread.processFrame() in /home/caiyi/repos/Danmaku!/DanmakuEngine/Threading/GameThread.cs:line 377
```

**Comment by Cai1Hsu** [comment]
Fixed, seems we can't allocate command list structures in a continuous memory.
